# Built with https://typeof.net/Iosevka/customizer

## Niosevka, a PragmataPro styled variant with higher underscore, trimed weights and normal width.
[buildPlans.niosevka]
family = "Niosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.niosevka.variants]
  inherits = "ss08"

    [buildPlans.niosevka.variants.design]
    underscore = "above-baseline"

[buildPlans.niosevka.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.niosevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.niosevka.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.niosevka.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.niosevka.weights.bold]
shape = 700
menu = 700
css = 700

# normal width is enough for me
[buildPlans.niosevka.widths.normal]
shape = 500        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.




## Niosevka Fixed, fixed spacing variant of Niosevka
[buildPlans.niosevka-fixed]
family = "Niosevka Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

  [buildPlans.niosevka-fixed.variants]
  inherits = "ss08"

    [buildPlans.niosevka-fixed.variants.design]
    underscore = "above-baseline"

[buildPlans.niosevka-fixed.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.niosevka-fixed.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.niosevka-fixed.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.niosevka-fixed.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.niosevka-fixed.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.niosevka-fixed.widths.normal]
shape = 500
menu  = 5
css   = "normal"




## Niosevka Term, terminal spacing variant of Niosevka.
[buildPlans.niosevka-term]
family = "Niosevka Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true

  [buildPlans.niosevka-term.variants]
  inherits = "ss08"

    [buildPlans.niosevka-term.variants.design]
    underscore = "above-baseline"

[buildPlans.niosevka-term.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.niosevka-term.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.niosevka-term.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.niosevka-term.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.niosevka-term.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.niosevka-term.widths.normal]
shape = 500
menu  = 5
css   = "normal"
